name: 'fda_project'
version: '1.0.0'
config-version: 2

profile: 'fda_project'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

models:
  fda_project:
    staging:
      +materialized: view
    marts:
      +materialized: table
